// React hooks
import { useState } from 'react';

// API functions
import { getReviews } from './api/reviews';

// nextjs components
import Head from 'next/head'


// MUI components
import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';

import Container from '@mui/material/Container';

import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';

// our own components
import ReviewCard from './components/ReviewCard';
import ReviewForm from './components/ReviewForm'


export default function Home() {

  const [reviews, setReviews] = useState([])

  const loadAllReviews = () => {
    // I'm demonstrating 'bad practice' in the interest of concision;
    // ideally, API functions would be in a separate layer from rendering.
    getReviews()
      .then((data) => {
        setReviews(data)
    });
  }


  return (
    <div>
      <Head>
        <title>Adaptation Reviews.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            Adaptations Reviews
          </Typography>
        </Toolbar>
      </AppBar>

      <main>
        <Container maxWidth="md">

          {/* Because I need to overwrite reviews in my form (upon submission),
              I need to pass the reviews (so I can read it) & its setter (so I can overwrite it)
              down into the form component.

              We're *sharing state* between this top-level page component & the form. 
          */}
          <ReviewForm
            reviews={reviews}
            onReviewsChange={setReviews}
          />

          <Box
            sx={{
              pt: 2,
              pb: 2,
            }}
          >
            <Button
              variant="contained"
              onClick={loadAllReviews}
            >
              Load All Current Reviews
            </Button>
          </Box>

          {reviews.map((adaptation, index) => {
            return <ReviewCard
              key={index}
              rating={adaptation.rating}
              title={adaptation.title}
              comment={adaptation.comment}
            />
          })}

        </Container>
      </main>
    </div>
  )
}
