// react hooks
import { useState, useEffect } from 'react';

import { getAgencies } from '@utils/api/agencies'

// nextjs components
import Head from 'next/head'

// mui components
import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';

import AgencyCard from '@components/AgencyCard';
import NavBar from '@components/NavBar';


export default function Home() {

  const [agenciesData, setAgenciesData] = useState([])

  useEffect(
    // param1: callback / logic that should fire
    () => {

      getAgencies().then(
        (data) => {
          console.log(data)
          setAgenciesData(data)
        }
      )

    },
    // param 2: dependency array (here: empty, only fire when component mounts)
    []
  )

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <NavBar />

        <Container sx={{paddingTop:2}} component="main" maxWidth="xs">

          <Typography variant="h3">
            Space Agencies
          </Typography>
          <Box
            sx={{
              marginTop: 2,
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
            }}
          >
          </Box>
        </Container>

    </div>
  )
}
