import Head from "next/head";

// materialUI components
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';

export default function Home() {
  return (
    <>
      <Head>
        <title>MUI Example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxWidth="sm">
          <Box sx={{ my: 4 }}>
            example text
            {/* we'll add some content here.*/}
          </Box>
        </Container>
      </main>
    </>
  );
}
